name: release-apps

permissions:
  contents: write
  id-token: write        # for Azure OIDC
  pages: write
  packages: write

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  publish:
    name: release-apps
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup .NET SDK (for WinSW)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.25.5'

      - name: Install MinGW-w64 cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            binutils-mingw-w64-x86-64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix || true
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix || true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Conveyor
        run: |
          wget -q https://downloads.hydraulic.dev/conveyor/hydraulic-conveyor_21.0_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./hydraulic-conveyor_21.0_amd64.deb

      - name: Azure Login (Client Secret)
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Gradle clean
        run: ./gradlew clean

      - name: Clean Conveyor cache
        run: |
          rm -rf ~/.config/hydraulic
          rm -rf ~/.conveyor
          rm -rf ~/.cache/conveyor

      - name: Create cert files
        run: |
          echo "${{ secrets.CONVEYOR_APPLE_CERT }}" > apple.cer
          echo "${{ secrets.CONVEYOR_WINDOWS_CERT }}" > windows.cer

      - name: Build & Publish Release
        run: ./gradlew buildConveyorSiteRelease
        env:
          CONVEYOR_SIGNING_KEY: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          CONVEYOR_PAT: ${{ secrets.CONVEYOR_PAT }}
          CONVEYOR_AGREE_TO_LICENSE: "1"