name: release-apps

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  publish:
    name: release-apps
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    environment: production

    steps:
      - name: Bootstrap Arch Linux
        run: |
          pacman -Syu --noconfirm
          
          pacman -S --noconfirm git nodejs base-devel \
            mingw-w64-gcc mingw-w64-crt mingw-w64-binutils mingw-w64-winpthreads \
            zip unzip tar \
            azure-cli python \
            wget ca-certificates

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.103'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Azure Login (Client Secret)
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Build All Inputs
        run: |
          git config --global --add safe.directory /__w/desktop/desktop
          
          export LDFLAGS="-static -static-libgcc -static-libstdc++"
          chmod +x gradlew
          
          ./gradlew :daemon:installDist \
                    :composeApp:createDistributable \
                    :cli:installDist \
                    :composeApp:writeConveyorConfig

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v21.0
        with:
          command: make copied-site
          extra_flags: -f conveyor-release.conf --passphrase=env:PASSPHRASE
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          agree_to_license: 1
        env:
          CONVEYOR_SIGNING_KEY: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          CONVEYOR_PAT: ${{ secrets.CONVEYOR_PAT }}
          PASSPHRASE: ${{ secrets.CONVEYOR_PASSPHRASE }}
          CONVEYOR_AGREE_TO_LICENSE: "1"